version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "daily"
      time: "00:10"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    groups:
      npm-production:
        dependency-type: "production"
      npm-development:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:20"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
