import {
  THOUGHT_AGENT_CREATIVE_BRIEF,
  THOUGHT_V2_PROTOCOL_RELEASE,
} from "../../../../packages/thought-agent-protocol/src/index";

export const THOUGHT_AGENT_REGISTERED_SPEC_ID =
  THOUGHT_V2_PROTOCOL_RELEASE.spec.evmSpecId;
export const THOUGHT_AGENT_REGISTERED_SPEC_REF =
  THOUGHT_V2_PROTOCOL_RELEASE.spec.ref;
export const THOUGHT_AGENT_CONTRACT_SPEC_ID =
  THOUGHT_V2_PROTOCOL_RELEASE.spec.evmSpecId;
export const THOUGHT_AGENT_CONTRACT_SPEC_HASH =
  THOUGHT_V2_PROTOCOL_RELEASE.spec.evmSpecHash;
export const THOUGHT_AGENT_SPEC_SHA256_HEX =
  THOUGHT_V2_PROTOCOL_RELEASE.spec.sha256;
export const THOUGHT_AGENT_SPEC_BYTE_LENGTH =
  THOUGHT_V2_PROTOCOL_RELEASE.spec.byteLength;
export const THOUGHT_AGENT_SPEC_TEXT = THOUGHT_V2_PROTOCOL_RELEASE.spec.text;
export const THOUGHT_AGENT_CREATIVE_BRIEF_TEXT =
  THOUGHT_AGENT_CREATIVE_BRIEF.text;
export const THOUGHT_AGENT_CREATIVE_BRIEF_ID =
  THOUGHT_AGENT_CREATIVE_BRIEF.id;
export const THOUGHT_AGENT_CREATIVE_BRIEF_ARTIFACT_ID =
  THOUGHT_AGENT_CREATIVE_BRIEF.artifactId;
export const THOUGHT_AGENT_CREATIVE_BRIEF_SHA256_HEX =
  THOUGHT_AGENT_CREATIVE_BRIEF.sha256;
export const THOUGHT_AGENT_CREATIVE_BRIEF_BYTE_LENGTH =
  THOUGHT_AGENT_CREATIVE_BRIEF.byteLength;
