export const PULSE_REPOSITORY_URL = "https://github.com/inshell-art/pulse";

export const PULSE = {
  title: "pulse",
  subtitle: "Pricing sketch for the $PATH auction.",
  desmosUrl: "https://www.desmos.com/calculator/1d89f93d21",
  repositoryUrl: PULSE_REPOSITORY_URL,
  explanation: [
    "Pulse shapes the ask over time.",
    "A successful bid closes the current epoch and starts the next one.",
    "The next ask is raised by a time premium.",
    "Between sales, the ask decays toward the floor.",
    "Settlement samples the ask at sale time.",
  ],
  math: [
    "pump",
    "",
    "PTS = price-time scale",
    "elapsed time = sale time - previous curve start",
    "premium = elapsed time × PTS",
    "current ask = last price + premium",
    "current floor = last price",
    "",
    "",
    "drop",
    "",
    "ask(t) = b + floor(k / (t - a))",
    "(t - a) × (ask(t) - b) ≈ k",
    "",
    "b = floor",
    "k = curve constant",
    "a = anchor time",
  ].join("\n"),
  note: "This is the Desmos sketch behind Pulse. It is a source note, not implementation code.",
} as const;
