export const PULSE_REPOSITORY_URL = "https://github.com/inshell-art/pulse";

export const PULSE = {
  title: "pulse",
  subtitle: "Pricing sketch for the $PATH auction.",
  desmosUrl: "https://www.desmos.com/calculator/1d89f93d21",
  repositoryUrl: PULSE_REPOSITORY_URL,
  explanation: [
    "Pulse shapes the ask over time.",
    "A successful bid closes the current epoch and starts the next one.",
    "The next ask is raised by an initial premium.",
    "Between sales, the ask decays toward the floor.",
    "Equivalently, premium decays toward zero.",
    "Settlement samples the ask at sale time.",
  ],
  math: [
    "pump",
    "",
    "PTS = price-time scale",
    "elapsed time = sale time - previous curve start",
    "initial premium = elapsed time × PTS",
    "next floor = last price",
    "next ask = next floor + initial premium",
    "",
    "",
    "drop",
    "",
    "premium(t) = ask(t) - floor",
    "ask(t) = floor + premium(t)",
    "ask(t) = b + ⌊k / (t - a)⌋",
    "(t - a) × (ask(t) - b) ≈ k",
    "",
    "b = floor",
    "k = curve constant",
    "a = anchor time",
  ].join("\n"),
  note: [
    "This is the Desmos sketch behind Pulse.",
    "It is not implementation code.",
  ],
} as const;
