#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname -- "$0")/.."

MODE="${MODE:-devnet}"            # devnet | sepolia | mainnet
OUT=".env.${MODE}.local"          # <-- unified target
PATH_REPO="${PATH_REPO:-../path}" # adjust if needed
ADDR_JSON="$PATH_REPO/output/addresses.${MODE}.json"

command -v jq >/dev/null || {
	echo "Missing jq"
	exit 1
}

if [ ! -f "$ADDR_JSON" ]; then
	echo "!! Not found: $ADDR_JSON. Run your deploy in the path repo first."
	exit 1
fi

PULSE=$(jq -r '.pulse_auction' "$ADDR_JSON")
ADAPTER=$(jq -r '.path_minter_adapter' "$ADDR_JSON")
MINTER=$(jq -r '.path_minter' "$ADDR_JSON")
NFT=$(jq -r '.path_nft' "$ADDR_JSON")

# Basic validation
for k in PULSE ADAPTER MINTER NFT; do
	v="${!k}"
	if [[ -z "$v" || "$v" == "0x" || "$v" == "0x..." ]]; then
		echo "!! $k looks empty: '$v'"
		exit 1
	fi
done

# You may keep RPC per mode. For devnet we usually use localhost.
RPC="${VITE_RPC_URL:-http://127.0.0.1:5050/rpc}"

cat >"$OUT" <<EOF
# generated by sync-env-from-path.sh (mode=$MODE)
VITE_MODE=$MODE
VITE_RPC_URL=$RPC
VITE_PULSE_AUCTION=$PULSE
VITE_PATH_ADAPTER=$ADAPTER
VITE_PATH_MINTER=$MINTER
VITE_PATH_NFT=$NFT
EOF

echo "Wrote $OUT"
cat "$OUT"
